# Generated by Django 3.0.3 on 2020-04-16 12:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DC_blog', '0002_blog_thumb'),
    ]

    operations = [
        migrations.AddField(
            model_name='gitpost',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
